/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.toml --include-runtime=false worker/src/worker-configuration.d.ts` (hash: a5e86ea1f073d65a2fdc3d993a777772)
interface __BaseEnv_Env {
	DB: D1Database;
	ALLOWED_ORIGIN: "https://reviewmoa.kro.kr";
	AI_MODEL: "gpt-5-mini";
	OPENROUTER_MODEL: "openrouter/free";
	AI_DAILY_LIMIT: "40";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
