/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.toml --include-runtime=false worker/src/worker-configuration.d.ts` (hash: 642789725a0ddaba11aae23b80662a42)
interface __BaseEnv_Env {
	DB: D1Database;
	ALLOWED_ORIGIN: "https://reviewmoa.kro.kr";
	AI_MODEL: "gpt-5-mini";
	OPENROUTER_MODEL: "openrouter/free";
	AI_DAILY_LIMIT: "40";
	COLLECTOR_LEASE_MS: "120000";
	COLLECTOR_MAX_ATTEMPTS: "3";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
